informes:
    pattern:  /
    defaults: { _controller: "InventarioFrontBundle:Informes:index" }

informes_kardex:
    pattern:  /kardex
    defaults: { _controller: "InventarioFrontBundle:Informes:kardex" }

informes_mvtoterceros:
    pattern:  /mvtoterceros
    defaults: { _controller: "InventarioFrontBundle:Informes:mvtoterceros" }

informes_mvtovendedores:
    pattern:  /mvtovendedores
    defaults: { _controller: "InventarioFrontBundle:Informes:mvtovendedores" }

informes_histprecios:
    pattern:  /histprecios
    defaults: { _controller: "InventarioFrontBundle:Informes:histprecios" }

informes_rentabilidad:
    pattern:  /rentabilidad
    defaults: { _controller: "InventarioFrontBundle:Informes:rentabilidad" }

informes_kardexData:
    pattern:  /kardexData/{prod}/{desde}/{hasta}
    defaults: { _controller: "InventarioFrontBundle:Informes:kardexData" }

informes_kardexResumen:
    pattern:  /kardexResumen/{prod}
    defaults: { _controller: "InventarioFrontBundle:Informes:kardexResumen" }

informes_mvtotercerosData:
    pattern:  /mvtotercerosData/{ter}/{desde}/{hasta}
    defaults: { _controller: "InventarioFrontBundle:Informes:mvtotercerosData" }

informes_mvtovendedoresData:
    pattern:  /mvtovendedoresData/{ven}/{desde}/{hasta}
    defaults: { _controller: "InventarioFrontBundle:Informes:mvtovendedoresData" }

informes_histpreciosData:
    pattern:  /histpreciosData/{prod}/{desde}/{hasta}
    defaults: { _controller: "InventarioFrontBundle:Informes:histpreciosData" }

informes_rentabilidadData:
    pattern:  /rentabilidadData/{prod}/{desde}/{hasta}
    defaults: { _controller: "InventarioFrontBundle:Informes:rentabilidadData" }

informes_mvtomeses:
    pattern:  /mvtomeses
    defaults: { _controller: "InventarioFrontBundle:Informes:mvtomeses" }

informes_mvtoproductos:
    pattern:  /mvtoproductos
    defaults: { _controller: "InventarioFrontBundle:Informes:mvtoproductos" }

informes_rotacion:
    pattern:  /rotacion
    defaults: { _controller: "InventarioFrontBundle:Informes:rotacion" }
