<?php

namespace Proxies\__CG__\Inventario\FrontBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Terceros extends \Inventario\FrontBundle\Entity\Terceros implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'txtipdoc', 'txdocumento', 'txnomtercero', 'intipoter', 'txdescuento', 'txdiasdescuento', 'txdireccion', 'txtelefonos', 'inactivo', 'intipodesc', 'txdivipola', 'idlistaprecios');
        }

        return array('__isInitialized__', 'id', 'txtipdoc', 'txdocumento', 'txnomtercero', 'intipoter', 'txdescuento', 'txdiasdescuento', 'txdireccion', 'txtelefonos', 'inactivo', 'intipodesc', 'txdivipola', 'idlistaprecios');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Terceros $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxtipdoc($txtipdoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxtipdoc', array($txtipdoc));

        return parent::setTxtipdoc($txtipdoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxtipdoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxtipdoc', array());

        return parent::getTxtipdoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxdocumento($txdocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxdocumento', array($txdocumento));

        return parent::setTxdocumento($txdocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxdocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxdocumento', array());

        return parent::getTxdocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxnomtercero($txnomtercero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxnomtercero', array($txnomtercero));

        return parent::setTxnomtercero($txnomtercero);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxnomtercero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxnomtercero', array());

        return parent::getTxnomtercero();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntipoter($intipoter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntipoter', array($intipoter));

        return parent::setIntipoter($intipoter);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntipoter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntipoter', array());

        return parent::getIntipoter();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxdescuento($txdescuento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxdescuento', array($txdescuento));

        return parent::setTxdescuento($txdescuento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxdescuento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxdescuento', array());

        return parent::getTxdescuento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxdiasdescuento($txdiasdescuento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxdiasdescuento', array($txdiasdescuento));

        return parent::setTxdiasdescuento($txdiasdescuento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxdiasdescuento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxdiasdescuento', array());

        return parent::getTxdiasdescuento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxdireccion($txdireccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxdireccion', array($txdireccion));

        return parent::setTxdireccion($txdireccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxdireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxdireccion', array());

        return parent::getTxdireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxtelefonos($txtelefonos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxtelefonos', array($txtelefonos));

        return parent::setTxtelefonos($txtelefonos);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxtelefonos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxtelefonos', array());

        return parent::getTxtelefonos();
    }

    /**
     * {@inheritDoc}
     */
    public function setInactivo($inactivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInactivo', array($inactivo));

        return parent::setInactivo($inactivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getInactivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInactivo', array());

        return parent::getInactivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntipodesc($intipodesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntipodesc', array($intipodesc));

        return parent::setIntipodesc($intipodesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntipodesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntipodesc', array());

        return parent::getIntipodesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxdivipola(\Inventario\FrontBundle\Entity\Deptociudades $txdivipola = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxdivipola', array($txdivipola));

        return parent::setTxdivipola($txdivipola);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxdivipola()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxdivipola', array());

        return parent::getTxdivipola();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdlistaprecios(\Inventario\FrontBundle\Entity\Listaprecios $idlistaprecios = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdlistaprecios', array($idlistaprecios));

        return parent::setIdlistaprecios($idlistaprecios);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdlistaprecios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdlistaprecios', array());

        return parent::getIdlistaprecios();
    }

}
