inventario_front_homepage:
    pattern:  /inventario
    defaults: { _controller: InventarioFrontBundle:Default:index }


InventarioFrontBundle_clasifproductos:
    resource: "@InventarioFrontBundle/Resources/config/routing/clasifproductos.yml"
    prefix:   /clasifproductos

InventarioFrontBundle_productos:
    resource: "@InventarioFrontBundle/Resources/config/routing/productos.yml"
    prefix:   /productos

InventarioFrontBundle_terceros:
    resource: "@InventarioFrontBundle/Resources/config/routing/terceros.yml"
    prefix:   /terceros
    
InventarioFrontBundle_detdocumentos:
    resource: "@InventarioFrontBundle/Resources/config/routing/detdocumentos.yml"
    prefix:   /detdocumentos
    
InventarioFrontBundle_detlistaprecios:
    resource: "@InventarioFrontBundle/Resources/config/routing/detlistaprecios.yml"
    prefix:   /detlistaprecios
    
InventarioFrontBundle_tipdoc:
    resource: "@InventarioFrontBundle/Resources/config/routing/tipdoc.yml"
    prefix:   /tipdoc

InventarioFrontBundle_vendedores:
    resource: "@InventarioFrontBundle/Resources/config/routing/vendedores.yml"
    prefix:   /vendedores    
    
InventarioFrontBundle_masdocumentos:
    resource: "@InventarioFrontBundle/Resources/config/routing/masdocumentos.yml"
    prefix:   /masdocumentos    