inventario_front_homepage:
    pattern:  /inventario
    defaults: { _controller: InventarioFrontBundle:Default:index }


listTerceros:
    pattern:  /listterceros
    defaults: { _controller: InventarioFrontBundle:Default:listTerceros }


newTerceros:
    pattern:  /newterceros
    defaults: { _controller: InventarioFrontBundle:Default:newTerceros }
