<?php

namespace Proxies\__CG__\Inventario\FrontBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Masdocumentos extends \Inventario\FrontBundle\Entity\Masdocumentos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idmasdocumento', 'txnumdoc', 'fefecha', 'fevencimiento', 'txobservaciones', 'txcondpago', 'dbvalneto', 'dbvaliva', 'dbtotal', 'inidtipdoc', 'inidtercero', 'vendedoresvendedor');
        }

        return array('__isInitialized__', 'idmasdocumento', 'txnumdoc', 'fefecha', 'fevencimiento', 'txobservaciones', 'txcondpago', 'dbvalneto', 'dbvaliva', 'dbtotal', 'inidtipdoc', 'inidtercero', 'vendedoresvendedor');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Masdocumentos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdmasdocumento()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdmasdocumento();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmasdocumento', array());

        return parent::getIdmasdocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxnumdoc($txnumdoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxnumdoc', array($txnumdoc));

        return parent::setTxnumdoc($txnumdoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxnumdoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxnumdoc', array());

        return parent::getTxnumdoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setFefecha($fefecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFefecha', array($fefecha));

        return parent::setFefecha($fefecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFefecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFefecha', array());

        return parent::getFefecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFevencimiento($fevencimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFevencimiento', array($fevencimiento));

        return parent::setFevencimiento($fevencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFevencimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFevencimiento', array());

        return parent::getFevencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxobservaciones($txobservaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxobservaciones', array($txobservaciones));

        return parent::setTxobservaciones($txobservaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxobservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxobservaciones', array());

        return parent::getTxobservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxcondpago($txcondpago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxcondpago', array($txcondpago));

        return parent::setTxcondpago($txcondpago);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxcondpago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxcondpago', array());

        return parent::getTxcondpago();
    }

    /**
     * {@inheritDoc}
     */
    public function setDbvalneto($dbvalneto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDbvalneto', array($dbvalneto));

        return parent::setDbvalneto($dbvalneto);
    }

    /**
     * {@inheritDoc}
     */
    public function getDbvalneto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDbvalneto', array());

        return parent::getDbvalneto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDbvaliva($dbvaliva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDbvaliva', array($dbvaliva));

        return parent::setDbvaliva($dbvaliva);
    }

    /**
     * {@inheritDoc}
     */
    public function getDbvaliva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDbvaliva', array());

        return parent::getDbvaliva();
    }

    /**
     * {@inheritDoc}
     */
    public function setDbtotal($dbtotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDbtotal', array($dbtotal));

        return parent::setDbtotal($dbtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDbtotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDbtotal', array());

        return parent::getDbtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setInidtipdoc(\Inventario\FrontBundle\Entity\Tipdoc $inidtipdoc = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInidtipdoc', array($inidtipdoc));

        return parent::setInidtipdoc($inidtipdoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getInidtipdoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInidtipdoc', array());

        return parent::getInidtipdoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setInidtercero(\Inventario\FrontBundle\Entity\Terceros $inidtercero = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInidtercero', array($inidtercero));

        return parent::setInidtercero($inidtercero);
    }

    /**
     * {@inheritDoc}
     */
    public function getInidtercero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInidtercero', array());

        return parent::getInidtercero();
    }

    /**
     * {@inheritDoc}
     */
    public function setVendedoresvendedor(\Inventario\FrontBundle\Entity\Vendedores $vendedoresvendedor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVendedoresvendedor', array($vendedoresvendedor));

        return parent::setVendedoresvendedor($vendedoresvendedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getVendedoresvendedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVendedoresvendedor', array());

        return parent::getVendedoresvendedor();
    }

}
