parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: Inventario
    database_user: inventariomar
    database_password: 1nv3nt4r10m4r
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 1nv3n74r10r3pu35705m4r
    database_path: null
